[package]
name = "document-file-server"
version = "0.1.0"
authors = ["hrb-mizuno-shinya <mizuno.shinya@hrbrain.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
